### ISSUE TITLE
cant chat or use a command

### ISSUE THREAD

**Issue by mote166** [jackthehack21/koth#10]
when in a koth game no one in that game can chat or use a command

pocketmine: 3.9.1

**Comment by jackthehack21** [comment]
Players are allowed to chat my plugin does not touch that, commands are blocked by default you can change it in the config file.

**Comment by ZandercraftGames** [comment]
I think this was purposeful, since it does accept commands, but only KOTH ones which I understand because it stops the plugin from glitching out if someone uses another plugin to move out of the arena's world or switch gamemodes, but I definitely think chat should be allowed and also that it should send a message to the user saying that non-koth-related commands are disabled whilst in a game, instead of making the user think that their connection has froze/broke.

**Comment by ZandercraftGames** [comment]
I also think this issue should have been explored more deeply before closing it, as I can confirm that chat is blocked as well @jackthehack21.

**Comment by jackthehack21** [comment]
I need a server.log from someone with the chat issue then.
And for the commands disabled notification ill add it in beta4

**Comment by ZandercraftGames** [comment]
Thanks Jack. What level of debugging do you want?

**Comment by jackthehack21** [comment]
server.log catches all levels.

**Comment by ZandercraftGames** [comment]
Ahh okay. Sorry, I misunderstood it as being "server log".

**Comment by mote166** [comment]
ok so it turned out that i had the commands turned off in the config and once i turned it on the chat came back, and as zander said not only commands get blocked, even the chat gets blocked too

**Comment by jackthehack21** [comment]
I know what’s causing it, but I need someone’s log to confirm

**Comment by jackthehack21** [comment]
Fixed in beta4, option to disable chat has also been added alongside notifying the player they cannot do XYZ while in game.
